-- SELECT * FROM cars;
-- SELECT * FROM cars WHERE year BETWEEN 2000 AND 2008;
-- SELECT * FROM cars WHERE color IN ("Violet", "Pink", "Fuscia");
-- SELECT * FROM cars WHERE color LIKE "violet";
-- SELECT * FROM cars WHERE model LIKE "X%";
-- SELECT * FROM cars WHERE model LIKE "%a";
-- SELECT * FROM cars WHERE model LIKE "_";
-- SELECT * FROM cars WHERE model LIKE "X_";
-- SELECT * FROM cars WHERE make LIKE "_n%";
-- SELECT * FROM cars WHERE color is NULL;
-- SELECT * FROM cars WHERE color IS NOT NULL;
-- INSERT INTO cars (make, model, year, price)
    -- VALUES ("Tesla", "Model Y", 2022, 55555); 
-- SELECT * FROM cars WHERE make="Ford" AND year > 2000;
-- SELECT * FROM cars WHERE make="Ford" OR year > 2010 ORDER BY make, year;
-- SELECT * FROM cars WHERE make="Ford"
    -- OR year BETWEEN 2004 AND 2006 ORDER BY year, make;
-- SELECT * FROM cars WHERE color 
    -- NOT IN ("Violet", "Pink", "Fuscia", "Puce", "Crimson");
-- SELECT * FROM cars
    -- WHERE (make = "Ford" or make = "Volvo")
    -- AND price BETWEEN 20000 and 60000;
-- SELECT * FROM cars WHERE make = "FORD" COLLATE NOCASE;
-- SELECT "gamintojas: " || model FROM cars;
-- SELECT make ||"," || model as car, year, color FROM cars;
-- SELECT make, model, 2023 year AS age FROM cars;
-- SELECT make, model, year, price, ROUND(price / 1.21, 2) as price_ex_vat FROM cars;
-- SELECT min(year), max(year), avg(year) FROM cars;
-- SELECT min(price), avg(price), max(price) FROM cars;
-- SELECT make, model, min(price) FROM cars;
-- SELECT make, model, min(price) FROM cars WHERE make="Toyota";
-- SELECT make, model, year, min(price), as pigiausia, count(make) AS c
    -- FROM cars
    -- WHERE year > 1998
    -- GROUP BY make 
    -- HAVING c>1 
    -- ORDER BY pigiausia;
-- SELECT sum(price), count(price) as kiekis FROM cars;